### ISSUE TITLE
Installation not working on Mac

### ISSUE THREAD

**Issue by judithabk6** [eth-sri/fare#2]
ResolvePackageNotFound error when installing
A quick google search suggests to use "no builds" option when exporting the environment
`conda env export --no-builds > environment.yml`

Thank you in advance

**Comment by rand0musername** [comment]
Hi @judithabk6, thank you for interest in our work. We've just pushed a more compact environment file and made some tweaks to the build scripts---we tested on ubuntu and mac and it worked but feel free to reopen this issue if you're still struggling.
